//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BookApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        internal static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        internal static string UseTheSearchFunction {
            get {
                return ResourceManager.GetString("UseTheSearchFunction", resourceCulture);
            }
        }
        
        internal static string NoElementsFoundChangeParametersTryAgain {
            get {
                return ResourceManager.GetString("NoElementsFoundChangeParametersTryAgain", resourceCulture);
            }
        }
        
        internal static string NoReadBooksSavedMessage {
            get {
                return ResourceManager.GetString("NoReadBooksSavedMessage", resourceCulture);
            }
        }
        
        internal static string BooksRead {
            get {
                return ResourceManager.GetString("BooksRead", resourceCulture);
            }
        }
        
        internal static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        internal static string CreateNewUserDisclaimer {
            get {
                return ResourceManager.GetString("CreateNewUserDisclaimer", resourceCulture);
            }
        }
        
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string BookDetails {
            get {
                return ResourceManager.GetString("BookDetails", resourceCulture);
            }
        }
        
        internal static string PreviewUnavailable {
            get {
                return ResourceManager.GetString("PreviewUnavailable", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        internal static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        internal static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string NoUserAvailableDisclaimer {
            get {
                return ResourceManager.GetString("NoUserAvailableDisclaimer", resourceCulture);
            }
        }
        
        internal static string ToggleDeleteMode {
            get {
                return ResourceManager.GetString("ToggleDeleteMode", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string InternetConnectionIsNotAvailableMessage {
            get {
                return ResourceManager.GetString("InternetConnectionIsNotAvailableMessage", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string SearchByTitle {
            get {
                return ResourceManager.GetString("SearchByTitle", resourceCulture);
            }
        }
        
        internal static string SearchByAuthor {
            get {
                return ResourceManager.GetString("SearchByAuthor", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string SearchBooks {
            get {
                return ResourceManager.GetString("SearchBooks", resourceCulture);
            }
        }
        
        internal static string BooksFoundCounterFormat {
            get {
                return ResourceManager.GetString("BooksFoundCounterFormat", resourceCulture);
            }
        }
        
        internal static string SearchReadBooks {
            get {
                return ResourceManager.GetString("SearchReadBooks", resourceCulture);
            }
        }
        
        internal static string BooksReadCounterFormat {
            get {
                return ResourceManager.GetString("BooksReadCounterFormat", resourceCulture);
            }
        }
        
        internal static string SearchForBooks {
            get {
                return ResourceManager.GetString("SearchForBooks", resourceCulture);
            }
        }
        
        internal static string ReadBooksList {
            get {
                return ResourceManager.GetString("ReadBooksList", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string WelcomeUserFormat {
            get {
                return ResourceManager.GetString("WelcomeUserFormat", resourceCulture);
            }
        }
    }
}
